"""
Upstream required input paths for gate freshness checking.

Maps gate_id → list of artifact paths whose modification times are checked
against the gate result's evaluated_at timestamp in gate_pass_recorded.

If any listed artifact exists and its mtime is strictly later than the gate
result's evaluated_at, the gate result is considered stale and the predicate
fails with STALE_UPSTREAM_MISMATCH.

Paths are relative to the repository root. Pass repo_root to resolve them;
if repo_root is None, they are resolved relative to the current working
directory (see runner.paths.resolve_repo_path).

Freshness-scope principle (2026-04-22)
--------------------------------------
Each path must be a **substantive source-of-truth input** whose modification
represents a real change to the data that the gate evaluated. Specifically:

- **Tier 3 source files** (human-placed project data): changes mean the
  project definition evolved and downstream gates must be re-evaluated.
- **Durable upstream phase outputs** (canonical artifacts written by prior
  phases): changes mean a prior phase was re-run and downstream gates that
  consumed its output must be re-evaluated.
- **Tier 2B read-only source documents** (work programme PDFs, grouped JSONs):
  changes are rare but when they occur they represent a real normative change.

The following are explicitly EXCLUDED from freshness tracking:

- **Generated helper artifacts** (call slices produced by ``call_slicer.py``,
  transport aids): these are deterministic derivatives of already-tracked
  source inputs and are regenerated on every run.
- **Directory paths** where the directory contains a mix of source files and
  generated artifacts: directory-level mtime conflates source and generated
  changes. Use specific file paths instead.

This table reflects the required_inputs described in CLAUDE.md §7 (Phase
Definitions and Gate Conditions) and the artifact_registry in
manifest.compile.yaml.
"""

UPSTREAM_REQUIRED_INPUTS: dict[str, list[str]] = {

    # entry gate for n01 — checks sources are present before Phase 1 starts.
    # Tracks only the Tier 3 call binding.  Work programme and call extract
    # presence is validated by the entry gate's own file-existence predicates
    # (g01_p03–g01_p06), not by freshness mtime comparison.  The call_extracts
    # directory is excluded because generate_call_slice() writes *.slice.json
    # into it on every run, creating a false-positive mtime bump.
    "gate_01_source_integrity": [
        "docs/tier3_project_instantiation/call_binding/selected_call.json",
    ],

    # exit gate for n01 — Phase 1 consumed call binding + Tier 2B sources.
    # selected_call.json is the sole substantive input whose change means
    # "different call target."  The work programme grouped JSONs are read-only
    # Tier 2B sources that essentially never change (PDFs imported once);
    # their staleness is covered by selected_call.json changes (different
    # work_programme field triggers different grouped JSON resolution).
    # The call_extracts directory is excluded: it contains the deterministic
    # call slice generated by Step 0 on every run.
    "phase_01_gate": [
        "docs/tier3_project_instantiation/call_binding/selected_call.json",
    ],

    # exit gate for n02 — Phase 2 consumed Phase 1 output + project brief.
    # call_analysis_summary.json is the durable Phase 1 output consumed by
    # Phase 2.  project_brief/ is a Tier 3 source directory — but we track
    # the specific files to avoid mtime conflation from unrelated siblings.
    "phase_02_gate": [
        "docs/tier4_orchestration_state/phase_outputs/phase1_call_analysis/call_analysis_summary.json",
        "docs/tier3_project_instantiation/project_brief/concept_note.md",
        "docs/tier3_project_instantiation/project_brief/project_summary.json",
        "docs/tier3_project_instantiation/project_brief/strategic_positioning.md",
    ],

    # exit gate for n03 — Phase 3 consumed Phase 2 output + WP and objectives seeds
    "phase_03_gate": [
        "docs/tier4_orchestration_state/phase_outputs/phase2_concept_refinement/concept_refinement_summary.json",
        "docs/tier3_project_instantiation/architecture_inputs/workpackage_seed.json",
        "docs/tier3_project_instantiation/architecture_inputs/objectives.json",
    ],

    # exit gate for n04 — Phase 4 consumed Phase 3 output + call duration + consortium roles + WP seed bounds
    "phase_04_gate": [
        "docs/tier4_orchestration_state/phase_outputs/phase3_wp_design/wp_structure.json",
        "docs/tier3_project_instantiation/call_binding/selected_call.json",
        "docs/tier3_project_instantiation/consortium/roles.json",
        "docs/tier3_project_instantiation/architecture_inputs/workpackage_seed.json",
        "docs/tier4_orchestration_state/phase_outputs/phase4_gantt_milestones/scheduling_constraints.json",
    ],

    # exit gate for n05 — Phase 5 consumed Phase 2 output + impact seeds + Tier 2B extracts
    "phase_05_gate": [
        "docs/tier4_orchestration_state/phase_outputs/phase2_concept_refinement/concept_refinement_summary.json",
        "docs/tier3_project_instantiation/architecture_inputs/outcomes.json",
        "docs/tier3_project_instantiation/architecture_inputs/impacts.json",
        "docs/tier2b_topic_and_call_sources/extracted/expected_outcomes.json",
        "docs/tier2b_topic_and_call_sources/extracted/expected_impacts.json",
    ],

    # exit gate for n06 — Phase 6 consumed Phases 3+4+5 outputs + consortium + risks
    "phase_06_gate": [
        "docs/tier4_orchestration_state/phase_outputs/phase3_wp_design/wp_structure.json",
        "docs/tier4_orchestration_state/phase_outputs/phase4_gantt_milestones/gantt.json",
        "docs/tier4_orchestration_state/phase_outputs/phase5_impact_architecture/impact_architecture.json",
        "docs/tier3_project_instantiation/consortium/partners.json",
        "docs/tier3_project_instantiation/architecture_inputs/risks.json",
        "docs/tier3_project_instantiation/call_binding/compliance_profile.json",
    ],

    # exit gate for n07 — Phase 7 consumed Phases 3+4+6 outputs + integration dirs.
    # Integration dirs (received/, validation/) are kept as directory paths:
    # their content is externally placed (budget responses), not generated by
    # the runner.  A new file in received/ is a real source-of-truth change.
    "gate_09_budget_consistency": [
        "docs/tier4_orchestration_state/phase_outputs/phase3_wp_design/wp_structure.json",
        "docs/tier4_orchestration_state/phase_outputs/phase4_gantt_milestones/gantt.json",
        "docs/tier4_orchestration_state/phase_outputs/phase6_implementation_architecture/implementation_architecture.json",
        "docs/integrations/lump_sum_budget_planner/received",
        "docs/integrations/lump_sum_budget_planner/validation",
    ],

    # exit gate for n08a — Excellence section consumed budget gate + Tier 3/4 inputs
    "gate_10a_excellence_completeness": [
        "docs/tier4_orchestration_state/phase_outputs/phase7_budget_gate/budget_gate_assessment.json",
        "docs/tier5_deliverables/proposal_sections/excellence_section.json",
    ],

    # exit gate for n08b — Impact section consumed budget gate + impact architecture
    "gate_10b_impact_completeness": [
        "docs/tier4_orchestration_state/phase_outputs/phase7_budget_gate/budget_gate_assessment.json",
        "docs/tier5_deliverables/proposal_sections/impact_section.json",
    ],

    # exit gate for n08c — Implementation section consumed budget gate + WP/Gantt/impl
    "gate_10c_implementation_completeness": [
        "docs/tier4_orchestration_state/phase_outputs/phase7_budget_gate/budget_gate_assessment.json",
        "docs/tier5_deliverables/proposal_sections/implementation_section.json",
    ],

    # exit gate for n08d — Assembly consumed all three section artifacts
    "gate_10d_cross_section_consistency": [
        "docs/tier5_deliverables/proposal_sections/excellence_section.json",
        "docs/tier5_deliverables/proposal_sections/impact_section.json",
        "docs/tier5_deliverables/proposal_sections/implementation_section.json",
        "docs/tier5_deliverables/assembled_drafts/part_b_assembled_draft.json",
    ],

    # exit gate for n08e — Review consumed assembled Part B draft
    "gate_11_review_closure": [
        "docs/tier5_deliverables/assembled_drafts/part_b_assembled_draft.json",
        "docs/tier5_deliverables/review_packets/review_packet.json",
    ],

    # exit gate for n08f — Revision consumed review packet + assembled draft + status
    "gate_12_constitutional_compliance": [
        "docs/tier4_orchestration_state/phase_outputs/phase8_drafting_review/drafting_review_status.json",
        "docs/tier5_deliverables/assembled_drafts/part_b_assembled_draft.json",
        "docs/tier5_deliverables/final_exports/final_export.json",
    ],
}
